name: release harmony with manual run on a given tag

on: 
  workflow_dispatch:
    inputs:
      inputtag: 
        decription: 'tag value to create the release'
        required: true

jobs:
  check:
    name: Per-check for current tag
    runs-on: ubuntu-18.04
    continue-on-error: false
    outputs:
      tag_annotated: ${{ steps.check-tag-annotated.outputs.tag_annotated }}

    steps:
      - name: Checkout harmony core code
        uses: actions/checkout@v2
        with:
          path: harmony
          ref: ${{ github.event.inputs.inputtag }}
          fetch-depth: 0

      - name: Check tag annotated
        id: check-tag-annotated
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1)
          if git rev-parse $VERSION^{tag} -- &>/dev/null
          then
            echo "::set-output name=tag_annotated::true"
          else
            echo "::set-output name=tag_annotated::false"
          fi
        working-directory: harmony